name: baidunetdisk
services:
  baidunetdisk:
    image: johngong/baidunetdisk:latest
    container_name: baidunetdisk
    deploy:
      resources:
        reservations:
          memory: 1024M
    ports:
      - 5800:5800
      - 5900:5900
    volumes:
      - /DATA/AppData/baidunetdisk/config:/config
      - /DATA/Downloads:/config/Downloads
    environment:
      - VNC_PASSWORD=vncpassword
    restart: unless-stopped
    network_mode: bridge
    privileged: false

x-casaos:
  architectures:
    - amd64
    - arm64
  main: baidunetdisk
  store_app_id: baidunetdisk
  author: Cp0204
  developer: Baidu Inc.
  category: Downloader
  description:
    en_us: Baidu Netdisk is a cloud storage product carefully crafted by Baidu for users, providing huge space. Full format files such as photos, videos, documents, and compressed files can be backed up to the cloud with just one click, providing you with comprehensive data protection. No matter the size of the files, you can share them with others with just one click, improving work and learning efficiency.
    zh_cn: 百度网盘是百度为用户精心打造的云存储产品，提供超大空间。照片、视频、文档、压缩包等全格式文件一键备份到云端，全方位为你数据保驾护航，无论文件大小一键分享他人，提升工作学习效率。
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/baidunetdisk/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/baidunetdisk/screenshot-1.png
  tagline:
    en_us: Run BaiduNetDisk with Crossover and VNC support
    zh_cn: VNC运行百度网盘
  tips:
    before_install:
      en_us: |
        Default access password: `vncpassword`, can be changed by environment variable `VNC_PASSWORD`.

        1. default VNC port 5900, if you don't use VNC client to connect you can remove the 5900 mapping.

        2. It can also be accessed through a browser using novnc.

        3. Note: If Baidu.com pops up an upgrade prompt inside the container, Please ignore it.


        [Project documentation](https://hub.docker.com/r/johngong/baidunetdisk)
      zh_cn: |
        默认访问密码：`vncpassword`，可通过环境变量`VNC_PASSWORD`修改。

        1. 默认VNC端口5900，如果不用VNC客户端连接可删除5900映射。

        2. 也可以通过浏览器用novnc访问。

        3. 注意：如果容器内部百度网盘弹出升级提示，请忽略。


        [项目文档](https://hub.docker.com/r/johngong/baidunetdisk)
  index: /
  port_map: "5800"
  scheme: http
  title:
    en_us: BaiduNetDisk
    zh_cn: 百度网盘
