version: "3.8"
name: ttydbridge
services:
  ttydbridge:
    # build: .
    # image: ttydbridge
    image: cp0204/ttydbridge:latest
    container_name: ttydbridge
    environment:
      EXEC_DIR: "/opt"
      START_COMMAND: "login"
      PORT: "2222"
    volumes:
      - /opt:/opt
    network_mode: bridge
    pid: host
    privileged: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 8M

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: ttydbridge
  store_app_id: ttydbridge
  category: Developer
  author: Cp0204
  developer: Cp0204
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/ttydbridge/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/ttydbridge/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/ttydbridge/screenshot-2.png
  description:
    en_us: ttydBridge acts as a "bridge" to the host environment, allowing you to easily access and use the host terminal in a web. It is built on ttyd and runs in a containerized manner, providing a secure and convenient remote endpoint experience.
    zh_cn: ttydBridge 如一座“桥”，连通了宿主机环境，让你在浏览器中轻松访问和使用宿主机终端。它基于 ttyd 构建，并以容器化的方式运行，提供了安全、便捷的远程终端体验。
  tagline:
    en_us: Easy access to the host terminal in web
    zh_cn: 在浏览器中轻松访问宿主机终端
  title:
    en_us: ttydBridge
  tips:
    before_install:
      en_us: |
        If you are using ZimaOS, the login command is missing:
        1. Change the environment variable `START_COMMAND` to `bash` ;
        2. And set the `HTTP_USERNAME` `HTTP_PASSWORD` variables to add HTTP authentication.

        [Official DOC](https://hub.docker.com/r/cp0204/ttydbridge)
      zh_cn: |
        如果你正在使用 ZimaOS ，由其缺少 login 命令：
        1. 请把环境变量 `START_COMMAND` 改为 `bash` ；
        2. 并设置 `HTTP_USERNAME` `HTTP_PASSWORD` 变量，以增加 HTTP 鉴权。

        [官方文档](https://hub.docker.com/r/cp0204/ttydbridge)
  port_map: "2222"
  scheme: http
  index: /
