name: filecodebox
services:
  filecodebox:
    image: lanol/filecodebox:beta
    container_name: filecodebox
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 12345
        published: 12345
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/filecodebox/data
        target: /app/data
    x-casaos:
      ports:
        - container: '12345'
          description:
            en_us: Port
            zh_cn: 端口
      volumes:
        - container: /app/data
          description:
            en_us: Data directory.
            zh_cn: 数据目录
x-casaos:
  architectures:
    - amd64
    - arm64
  main: filecodebox
  store_app_id: filecodebox
  category: WEB
  author: Cp0204
  developer: vastsa
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/filecodebox/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/filecodebox/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/filecodebox/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/filecodebox/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/filecodebox/thumbnail.png
  description:
    en_us: FileCodeBox is a simple and easy-to-use file sharing platform that allows you to share files and texts anonymously without registration. Users can upload files by copying, pasting or dragging and dropping, and enjoy the security of password sharing, error count limit and IP upload count limit. It supports multi-language, one-click docker deployment, and free to expand the storage engine.
    zh_cn: FileCodeBox 是一个简洁易用的文件分享平台，无需注册即可匿名分享文件和文本。用户可通过复制粘贴或拖拽上传，享有口令分享、错误次数限制和IP上传次数限制等安全保障。支持多语言，一键部署docker，可自由拓展存储引擎。
  tagline:
    en_us: Anonymous Passcode Sharing Files
    zh_cn: 像拿快递一样取文件
  title:
    en_us: FileCodeBox
    zh_cn: 文件快递柜
  tips:
    before_install:
      en_us: 'Default open is admin backend, password: `FileCodeBox2023`; remove `/#/admin` is user frontend.'
      zh_cn: 默认打开为管理后台，密码：`FileCodeBox2023`；去掉 `/#/admin` 是用户前端。
  port_map: '12345'
  scheme: http
  index: /#/admin
