name: tinymediamanager
services:
  tinymediamanager:
    environment:
      GROUP_ID: "0"
      USER_ID: "0"
      TZ: Asia/Hong_Kong
    image: tinymediamanager/tinymediamanager:5-test
    container_name: tinymediamanager
    deploy:
      resources:
        reservations:
          memory: "1024M"
    network_mode: bridge
    ports:
      - target: 4000
        published: "4000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/tinymediamanager/config
        target: /config
      - type: bind
        source: /DATA/Media
        target: /DATA/Media
      - type: bind
        source: /media
        target: /media
      - type: bind
        source: /mnt
        target: /mnt
x-casaos:
  architectures:
    - amd64
    - arm64
  author: Cp0204
  category: Media
  description:
    en_us: tinyMediaManager is a media management tool written in Java/Swing. It is designed to provide a simple and intuitive interface for organizing and managing your media collection.
    zh_cn: tinyMediaManager 是一个用 Java/Swing 编写的媒体管理工具。它旨在为您的媒体收藏提供简单直观的界面，方便组织和管理。
  developer: tinyMediaManager
  main: tinymediamanager
  tagline:
    en_us: Media management tool
    zh_cn: 媒体管理工具
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/tinyMediaManager/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/tinyMediaManager/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/tinyMediaManager/screenshot-2.png
  tips:
  title:
    en_us: tinyMediaManager
  port_map: "4000"
  scheme: http
